## <center> <font color='blue'> <b> Shapes </b> </font> </center>

In [6]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, SimpleRNN, Dense 


- N = number of samples
- T = sequence length
- D = number of input features
- M = number of hidden units
- K = number of output units

In [3]:
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [7]:
# Make an RNN
M = 5 # numbe of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [9]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57 (228.00 Byte)
Trainable params: 57 (228.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
# we have 3 layers
model.layers

In [16]:
model.layers[0].get_weights()

[]

In [18]:
model.layers[1].get_weights()

[array([[ 0.13106674, -0.22770149, -0.3609569 ,  0.68683106,  0.68256456],
        [-0.70461833,  0.30594808,  0.4205361 , -0.22449201,  0.35562223],
        [ 0.48581475,  0.4715523 ,  0.18805414, -0.6843454 , -0.7347472 ]],
       dtype=float32),
 array([[-0.05307329, -0.32266968,  0.9437103 ,  0.04839824,  0.01166544],
        [-0.14279969,  0.3933387 ,  0.09161005,  0.49771234,  0.7541771 ],
        [-0.94671094,  0.20606092,  0.02809924, -0.1692499 , -0.17844371],
        [ 0.18354385,  0.6360593 ,  0.21423557,  0.40712726, -0.5916847 ],
        [ 0.21642894,  0.5423436 ,  0.23309244, -0.74534684,  0.22169332]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [19]:
model.layers[2].get_weights()

[array([[ 0.5727223 , -0.9049505 ],
        [ 0.5992048 , -0.39434803],
        [ 0.86093557, -0.06410849],
        [ 0.21143854, -0.77533203],
        [-0.89546096, -0.22916865]], dtype=float32),
 array([0., 0.], dtype=float32)]

We are going to concentrate in layer 1.

Check their shapes

- First output is input -> hidden (D x M)
- Second is hidden -> hidden (M x M)
- Third is the bias term (vector of length M)


In [21]:
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)


(3, 5) (5, 5) (5,)


In [8]:
# make a prediction (of course it doesnt make sense, is just for illustrative purpose)
yhat = model.predict(X)
yhat

1/1 [==============================] - 0s 353ms/step


array([[-0.21117096,  0.65983284]], dtype=float32)

Now, let's manually calculate a prediction.

In [23]:
# first, we get the weights
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [28]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample

Yhats = [] # where we store the outputs
for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo # we only care about this value on the last iteration
    Yhats.append(y)
    
    #assign h to h_last
    h_last = h
    
#print the final output
print(Yhats[-1])


[-0.21117087  0.65983285]


We got the same values as with model.predict.